<b><h1><center>Numpy</center></h1></b>

# **Numpy**
NumPy (Numerical Python) is the fundamental library for numerical computing in Python.

It provides a powerful object called ndarray (N-dimensional array) that allows us to store and process large amounts of numerical data much faster and more efficiently than Python's built-in data structures.

Think of NumPy as the engine of Data Science.

In order to use the numpy libraries we have to import the library

In [5]:
import numpy as np


# **Array**

An array is a collection of elements stored in a single continuous block of memory, where all elements have the same data type.

Unlike Python lists, NumPy arrays are designed specifically for fast mathematical and scientific computations.

A NumPy array is

- Homogeneous (same data type)
- Fixed Size
- Indexed
- Mutable
- Stored in Contiguous Memory
- Optimized for Numerical Computing

np.array(list, datatype=float)

datatype is optional 

In [6]:
a = np.array([3, 5, 5, 7, 9])
print(a)
print(type(a))

[3 5 5 7 9]
<class 'numpy.ndarray'>


# **Types of Array**

### **1D Array (Vector)**
Contains only one axis.

In [9]:
a = np.array([3, 4, 6, 7, 9])
print(a)
print(a.ndim)     # it give the dimenion of array either it is 1d or 2d or 3d

[3 4 6 7 9]
1


### **2D Array (Matrix)**
Contains rows and columns.

In [13]:
a = np.array([[2, 4], [4, 6], [3, 5]])
print(a)
print(a.ndim)

[[2 4]
 [4 6]
 [3 5]]
2


### **3D Array (Tensor)**
Collection of multiple matrices.

In [14]:
a = np.array([
    [[1, 3], 
     [2, 4]], 
    [[3, 5], 
     [4, 6]]
])

print(a)
print(a.ndim)

[[[1 3]
  [2 4]]

 [[3 5]
  [4 6]]]
3


# **Creating Array**

### **array**
Creates a NumPy array from existing data like lists, tuples, or nested lists.

In [15]:
li = [3, 5, 6, 7, 8]

a = np.array(li)

print(a)
print(type(a))

[3 5 6 7 8]
<class 'numpy.ndarray'>


### **arange**
Creates an array containing evenly spaced values within a specified interval.

It works like Python's range(), but returns a NumPy array.

np.arange(start, stop, step)

In [19]:
a = np.arange(1, 11)
print(a)

b = np.arange(1, 11, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


### **reshape**

Changes the shape of an array without changing its data.

array.reshape(rows, columns)

In [25]:
a = np.arange(1, 11).reshape(5, 2)
print(a)

b = np.arange(1, 21).reshape(5, 4)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [39]:
a = np.arange(1, 17, dtype=float).reshape(2, 2, 4)
print(a)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


### **ones**
Creates an array filled entirely with ones.

np.ones(shape)

In [31]:
np.ones((2, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### **zeros**

Creates an array filled entirely with zeros.

np.zeros(shape)

In [32]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **random**
The np.random module is used to generate random numbers for simulations, testing, and machine learning.

In [37]:
np.random.random(10)

array([0.65881349, 0.14840064, 0.2875843 , 0.47060326, 0.33825308,
       0.96367034, 0.84331692, 0.83181674, 0.76879858, 0.80774085])

### **identity**

Creates an identity matrix.

An identity matrix is a square matrix where:

- All diagonal elements are 1
- All other elements are 0

np.identity(shape)

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **linspace**

Creates a specified number of equally spaced values between two endpoints.

Unlike arange(), you specify the number of values, not the step size.

np.linspace(start, stop, num=50)

**Parameters**

- start → Starting value
- stop → Ending value (included)
- num → Number of equally spaced values

In [48]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

# **Summary**

| Function              | Purpose                              | Example                          |
| --------------------- | ------------------------------------ | -------------------------------- |
| `np.array()`          | Create array from existing data      | `np.array([1,2,3])`              |
| `np.arange()`         | Evenly spaced values with a step     | `np.arange(0,10,2)`              |
| `reshape()`           | Change array shape                   | `arr.reshape(3,4)`               |
| `np.zeros()`          | Array of zeros                       | `np.zeros((2,3))`                |
| `np.ones()`           | Array of ones                        | `np.ones((3,3))`                 |
| `np.identity()`       | Identity matrix                      | `np.identity(4)`                 |
| `np.linspace()`       | Fixed number of evenly spaced values | `np.linspace(0,1,5)`             |
| `np.random.rand()`    | Random floats                        | `np.random.rand(2,2)`            |
| `np.random.randint()` | Random integers                      | `np.random.randint(1,10,size=5)` |


<br>

# **Array Attribute**

Array attributes are built-in properties that describe an array.

### **ndim**

ndim stands for Number of Dimensions.

It tells us how many axes (dimensions) an array has.

In [52]:
a = np.arange(10)
print(a.ndim)

b = np.arange(20).reshape(4, 5)
print(b.ndim)

c = np.arange(20).reshape(2, 2, 5)
print(c.ndim)

1
2
3


### **shape**
shape returns the size of every dimension in the form of a tuple.

It tells us how many elements exist along each axis.

In [53]:
a = np.arange(10)
print(a.shape)

b = np.arange(20).reshape(4, 5)
print(b.shape)

c = np.arange(20).reshape(2, 2, 5)
print(c.shape)

(10,)
(4, 5)
(2, 2, 5)


### **size**

size returns the total number of elements in the array.

In [54]:
c = np.arange(20).reshape(2, 2, 5)

print(c.size)

20


### **itemsize**
itemsize returns the memory occupied by one element, measured in bytes.

In [60]:
c = np.arange(20, dtype=np.int32)

d = np.arange(20, dtype=np.int64)

print(c.itemsize)
print(d.itemsize)

4
8


### **Common Data Types**

| Data Type | Bytes |
| --------- | ----: |
| int8      |     1 |
| int16     |     2 |
| int32     |     4 |
| int64     |     8 |
| float32   |     4 |
| float64   |     8 |


### **dtype**

dtype stands for Data Type.

It tells us what type of data is stored in the array.

In [61]:
a = np.array([2, 3, 4, 5])
b = np.array(["salman", "farhad"])

print(a.dtype)
print(b.dtype)

int64
<U6


### **astype**
This is not an attrubute as it is a method.

astype() creates a new array with a different data type.

It does not modify the original array unless you assign the result back.

In [63]:
a = np.array([3, 4, 5, 6])
print(a)

c = a.astype(float)

print(c)

[3 4 5 6]
[3. 4. 5. 6.]


# **Summary**

| Attribute / Method | Purpose                     | Returns              |
| ------------------ | --------------------------- | -------------------- |
| `ndim`             | Number of dimensions        | Integer              |
| `shape`            | Size of each dimension      | Tuple                |
| `size`             | Total number of elements    | Integer              |
| `itemsize`         | Memory used by one element  | Integer (bytes)      |
| `dtype`            | Data type of elements       | `numpy.dtype` object |
| `astype()`         | Converts to a new data type | New NumPy array      |


<br>

# **Array Operation**

### **1. Scalar Arithmetic Operations**
When an array is operated with a single number (scalar), NumPy performs the operation on every element.

In [65]:
a = np.array([1, 2, 3, 4, 5])

a + 2

array([3, 4, 5, 6, 7])

In [66]:
a*3

array([ 3,  6,  9, 12, 15])

In [67]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [68]:
a**2

array([ 1,  4,  9, 16, 25])

In [69]:
a-1

array([0, 1, 2, 3, 4])

<br>

### **2. Vector Arithmetic Operations**
When two arrays perform arithmetic operations element by element, it is called vector arithmetic.

Both arrays should usually have the same shape (or be broadcast-compatible).

In [70]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
a+b

array([2, 4, 6, 8])

In [71]:
a*b

array([ 1,  4,  9, 16])

In [72]:
a/b

array([1., 1., 1., 1.])

In [73]:
a**2

array([ 1,  4,  9, 16])

In [74]:
a-b

array([0, 0, 0, 0])

<br>

### **3. Relational (Comparison) Operations**
Relational operations compare elements and return Boolean values (True or False).

These are heavily used in filtering data.

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])

In [91]:
print(a>1)
print(b<3)
print(a==4)
print(a!=3)
print(a%2==0)

[False  True  True  True]
[ True  True False False]
[False False False  True]
[ True  True False  True]
[False  True False  True]


### **4. Logical Operations**

These combine multiple conditions.

In [84]:
a = np.array([1, 2, 3, 4])

(a>2) | (a==1)

array([ True, False,  True,  True])

In [92]:
b = np.array([3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12, 13])

print((b>5) & (b%2==0))

[False False False  True False  True  True False  True False  True False]


In [93]:
~(b>5)

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

# **Iteration on Array**

In [94]:
b = np.array([3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12, 13])

for i in b:
    print(i)

3
4
5
6
7
8
8
9
10
11
12
13


In [98]:
b = np.array([[1, 2, 3], [1, 2, 3], [1, 3, 4]])

for i in b:
    print(i)

[1 2 3]
[1 2 3]
[1 3 4]


In [100]:
for i in np.nditer(b):  # it convert the 2d or 3d into 1d array
    print(i)

1
2
3
1
2
3
1
3
4


# **Array Function**

### **min**
Returns the smallest element.

In [107]:
b = np.array([[1, 2, 3], [1, 2, 3], [1, 3, 4]])


print(np.min(b))
np.min(b, axis=1)

1


array([1, 1, 1])

### **max**
return the greatest element.

In [109]:
b = np.array([[1, 2, 3], [1, 2, 3], [1, 3, 4]])

print(np.max(b))
print(np.max(b,axis=1))

4
[3 3 4]


### **sum**

sum the element.

In [112]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.sum(a))

21


### **prod**

Multiply all the element.

In [113]:
print(np.prod(a))

720


### **mean**
Return average of array.

In [115]:
print(np.mean(a))

3.5


### **median**
Middle value of array.

In [116]:
np.median(a)

np.float64(3.5)

### **std**
Measures how spread out the data is.

In [117]:
np.std(a)

np.float64(1.707825127659933)

### **var**
Square of standard deviation.

In [118]:
np.var(a)

np.float64(2.9166666666666665)

### **dot**
It perform the dot product on matrix as the multiplicatoin matrix.

In [124]:
a = np.array([[1, 3, 4], [3, 4, 6]])
b = np.array([[3, 4, 5], [3, 5, 6], [3, 5, 6]])
np.dot(a, b)

array([[24, 39, 47],
       [39, 62, 75]])

### **exp**
The np.exp() function calculates the exponential value (eˣ) of every element in a NumPy array.

exp(x)=e**x

**where**

- e = Euler's Number
- e ≈ 2.718281828459045



In [127]:
print(np.e)  # it will give the value of euler's no.

b = np.array([[1, 2, 3], [1, 2, 3], [1, 3, 4]])

print(np.exp(b))

2.718281828459045
[[ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183 20.08553692 54.59815003]]


### **log**

np.log() calculates the natural logarithm (ln) of every element.

In [128]:
a = np.array([3, 5, 6])
print(np.log(a))

[1.09861229 1.60943791 1.79175947]


### **round**
Rounds every element to the nearest value.

np.round(array, decimals)

In [132]:
a = np.array([3.54, 54.656, 45.65, 4.55])
print(np.round(a, 2))
print(np.round(a))

[ 3.54 54.66 45.65  4.55]
[ 4. 55. 46.  5.]


### **floor**
Returns the greatest integer less than or equal to each value.

Simply remember

Always moves downward on the number line.

In [134]:
a = np.array([3.54, 54.656, 45.65, 4.55, -2.556])

print(np.floor(a))

[ 3. 54. 45.  4. -3.]


### **ceil**
Returns the smallest integer greater than or equal to each value.

Remember

Always moves upward on the number line.

In [135]:

a = np.array([3.54, 54.656, 45.65, 4.55, -2.556])

print(np.ceil(a))

[ 4. 55. 46.  5. -2.]


### **nditer**

It is used to iterate through every element of an array, regardless of its dimensions.

In [137]:
a = np.array([[3, 4], [4, 5,], [7, 8]])
for i in a:
    print(i)            # Normally

[3 4]
[4 5]
[7 8]


In [139]:
for i in np.nditer(a):
    print(i)

3
4
4
5
7
8


### **Transpose**
A transpose swaps the rows and columns of a matrix.

In [143]:
a = np.array([[3, 4], [4, 5,], [7, 8]])

print(a)

print("\n")


print(np.transpose(a))



[[3 4]
 [4 5]
 [7 8]]


[[3 4 7]
 [4 5 8]]


In [142]:
# shortcut

print(a.T)

[[3 4 7]
 [4 5 8]]


### **ravel**
ravel() converts a multidimensional array into a 1D array.

This process is called flattening.

In [146]:
a = np.array([[3, 4], [4, 5,], [7, 8]])

print(a)

print("\n")

print(np.ravel(a))

[[3 4]
 [4 5]
 [7 8]]


[3 4 4 5 7 8]


# **Array Stacking**

### **hstack**
hstack() means horizontal stack.

It joins arrays side by side (column-wise).

In [153]:
a = np.array([[3, 4], [4, 5,], [7, 8]])
b = np.array([[2, 6], [5, 6,], [0, 2]])
print(a)
print("\n")
print(b)


c = np.hstack((a, b))
print("\n")
print(c)

[[3 4]
 [4 5]
 [7 8]]


[[2 6]
 [5 6]
 [0 2]]


[[3 4 2 6]
 [4 5 5 6]
 [7 8 0 2]]


### **vstack**
vstack() means vertical stack.

It joins arrays one above another (row-wise).

In [156]:
a = np.array([3, 5, 7])
b = np.array([4, 6, 8])

print(np.hstack((a, b)))
print(np.vstack((a,b)))

[3 5 7 4 6 8]
[[3 5 7]
 [4 6 8]]


In [157]:
a = np.array([[3, 4], [4, 5,], [7, 8]])
b = np.array([[2, 6], [5, 6,], [0, 2]])

c = np.vstack((a, b))
print(c)

[[3 4]
 [4 5]
 [7 8]
 [2 6]
 [5 6]
 [0 2]]


# **Array Splitting**

### **hsplit**
hsplit() splits an array horizontally, which means it divides the columns into separate arrays.

In [178]:
a = np.array([[3, 4], [4, 5,], [7, 8]])

np.hsplit(a, 2)


[array([[3],
        [4],
        [7]]),
 array([[4],
        [5],
        [8]])]

In [179]:
a, b = np.hsplit(a, 2)       # array unpac

print(a)
print(b)

[[3]
 [4]
 [7]]
[[4]
 [5]
 [8]]


In [183]:
a = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])


print(np.hsplit(a, 2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


### **vsplit**
vsplit() splits an array vertically, which means it divides the rows into separate arrays.

In [185]:
a = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

np.vsplit(a, 2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

# **Array Indexing**

Indexing is the process of accessing one or more specific elements from an array using their position (index).

Every element in a NumPy array has an index.

### **1D indexing**

array[index]

In [187]:
a = np.array([3, 4, 5, 6, 7])
print(a[3])
print(a[0])

6
3


### **2D indexing**

array[row, column]

In [197]:
a = np.array([[ 0,  1,  2,  3],
            [ 4,  5,  6,  7],
            [ 8,  9, 10, 11],
            [12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]])
print(a[0,2])
print(a[3,-1])
print(a[2,-1])

2
15
11


### **3D indexing**

array[matrices, rows, columns]

In [196]:
b = np.array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

print(b)
print(b[1, 0, 1])
print(b[0, 0, 0])
print(b[0, 1, 1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
0
3


# **Array Slicing**
Slicing extracts multiple elements from an array.

Instead of retrieving one value, it retrieves a range of values.

array[start : stop : step]

### **1D Slicing**

array[start : stop : step]

In [203]:
a = np.array([3, 5, 6, 8, 6, 7, 5, 3, 4, 2, 1])
print(a[1:4])
print(a[3:8])
print(a[0:6:2])

[5 6 8]
[8 6 7 5 3]
[3 6 6]


### **2D Slicing**

array[row : row, column : column]

In [211]:
a = np.array([[ 0,  1,  2,  3],
            [ 4,  5,  6,  7],
            [ 8,  9, 10, 11],
            [12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]])

print(a[0, :])
print(a[:, 0])
print(a[1:, 3])
print(a[0::5, ::3])

[0 1 2 3]
[ 0  4  8 12 16 20]
[ 7 11 15 19 23]
[[ 0  3]
 [20 23]]


### **3D Slicing**

array[matrices : maatrices, rows : rows, columns : columns]

In [215]:
a = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

print(a[0, 1, :2])
print(a[::2,::2, ::2 ])

[3 4]
[[[ 0  2]
  [ 6  8]]

 [[18 20]
  [24 26]]]


<br>

---