**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here

null_vector = np.zeros((10), dtype=np.int8)
null_vector[4]=1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here
try:
    rows = int(input("enter no of rows"))
    columns = int(input("enter no of columns"))
except Exception as e:
    print(e)
arr = np.random.random((rows, columns))
print(arr)
print(np.mean(arr))

[[0.72906889 0.30416964]
 [0.34362079 0.5899725 ]]
0.4917079532014608


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [4]:
#Code here

def create_array(a, b):
    arr = np.zeros((a, b), dtype=np.int8)
    arr[: ,[0, -1]]=1
    arr[[0, -1], :]=1
    return arr

create_array(4, 4)

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]], dtype=int8)

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [5]:
#Code here

a = np.linspace(0.1, 0.9, 10)
print(a)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [6]:
#Code here

# no identity matrix must have same no of rows and columns

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [7]:
#Code here

a = np.arange(0, 5).reshape(1, 5).repeat(5, axis=0)
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [8]:
#code here

a = np.random.randint(1, 100, (10, 2))
point = np.array([2,3])
    
distance = (a-point)**2
result = np.sqrt(distance[:,0]+distance[:,1]).astype(int)
print(distance)
print(result)

[[6400 2500]
 [6084 8100]
 [4900  400]
 [   1   49]
 [3025 3364]
 [4225 2209]
 [4225  144]
 [2025 2116]
 [  25 1764]
 [   0 6241]]
[ 94 119  72   7  79  80  66  64  42  79]


In [9]:
distance = (a-point)**2
distance
(np.sum(distance, axis=1)**0.5).astype(int)

array([ 94, 119,  72,   7,  79,  80,  66,  64,  42,  79])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [10]:
#Code here
a = np.arange(1, 337).reshape(6, 7, 8)
a[1,5, 3]

np.int64(100)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [11]:
#Code here

inp = "1 2 3 4 -8 -10"
sp = inp.split(" ")
arr = np.array(sp, dtype=float)[::-1]
print(arr)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [12]:
#Code here

a = np.array([2, 3, 4, 5])
b = np.array([])
c = np.array([[2, 3], [4, 6]])
print(a.size)
print(b.size)
print(c.size)

4
0
4


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [13]:
#Code here
import numpy as np


def softmax(arr):
    if arr.ndim==1:
        num = np.exp(arr)
        den = np.sum(num)
    else:
        raise TypeError("array should be one dimension")
     
    return (num/den)
 
a = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
softmax(a)

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [14]:
#Coder here


a=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

b=np.array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

c=np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

def stack(*args):
    tpe = args
    for i in tpe:
        if type(i)!=np.ndarray:
            raise TypeError("type should be numpy array")
    stk = np.vstack(args)
    return stk

stack(a, b, c)
    

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

def create_date(a, b):
    if type(a)!=str and type(b)!=str:
        raise TypeError("data type should be str")
    start = np.datetime64(a)
    end = np.datetime64(b)
    return np.arange(start, end+np.timedelta64(1, "D"))

create_date("2020-11-25", "2020-11-30")

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

In [72]:
import datetime as dt

start = dt.datetime.strptime('2020-11-25', '%Y-%m-%d')
end = dt.datetime.strptime('2020-11-30', '%Y-%m-%d')


### `Q-14:` Subtract the mean of each row from a matrix.

In [16]:
#code here

a = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
print(a)

c = np.mean(a, axis=1).reshape(3, 1)
print(c)
print(a-c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [17]:
#Code here

a = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
print(a)

c = a[:,[0, 2, 1]]
c

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 3, 2],
       [4, 6, 5],
       [7, 9, 8]])

### `Q-16:` Replace odd elements in arrays with -1.

In [18]:
#Code here

a = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
print(a)

a[a%2!=0] = -1
a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[-1,  2, -1],
       [ 4, -1,  6],
       [-1,  8, -1]])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [19]:
#Code here

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

c = np.vstack((a, b))
np.max(c, axis=0)

array([6, 3, 1, 7, 8])

In [20]:
np.maximum(a, b)  # it is used to find the maximium no in two or more than two arraies

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [21]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3781, 2816, 6385, 6865, 8037],
       [ 826, 9790, 1279, 3422, 9525],
       [7758, 8930, 9882, 5367, 8852],
       [2020, 5383,  358, 9922, 5438],
       [ 556, 2248, 7167, 3063, 9817],
       [3094,  479, 1045, 6523, 9859],
       [4499, 2651, 8300, 3936, 5370],
       [6626, 3132, 4580, 8116, 5554]], dtype=int32)

In [22]:
#Code here
alternate = arr1[:, ::2]
normalize = (alternate-np.min(alternate))/(np.max(alternate)-np.min(alternate))
normalize

array([[0.35940781, 0.63282234, 0.80627887],
       [0.04913902, 0.09670307, 0.96251575],
       [0.77698446, 1.        , 0.89185216],
       [0.17450651, 0.        , 0.53338933],
       [0.02078958, 0.7149307 , 0.99317514],
       [0.28727425, 0.07213356, 0.99758505],
       [0.4347963 , 0.83389332, 0.52624948],
       [0.65812684, 0.44330113, 0.54556909]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [23]:
#Code here

def fun(arr, n):
    if type(arr)!=np.ndarray or n>len(arr) or n<1:
        raise Exception("Please put the correct value of n")
    a = np.sort(arr)[::-1]
    return a[n-1]
    
    
ar = np.array([12, 34, 40, 7, 1, 0])

fun(ar, 3)

np.int64(12)

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [24]:
#code here
import numpy as np
a = np.array([1, 2, 3])

b = np.repeat(a, 3)
c = np.tile(a, 3)

final = np.append(b, c)
final

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])