<b><h1><center>Numpy Advance</center></h1></b>

# **Array Vs List**

### **List**

- A list is a built-in Python data structure used to store a collection of objects.

- A list can contain different types of data.

- A Python list stores references (addresses) to separate Python objects.
- Slow Speed

### **Array**

- A NumPy array is a data structure designed to store large amounts of numerical data efficiently.

- Unlike lists, a NumPy array stores only one data type.

- A NumPy array stores values in one continuous block of memory.
  
- High Speed

In [2]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

3.1599974632263184


In [3]:
import sys

sys.getsizeof(a)

89095160

In [4]:
import numpy as np
import sys
import time

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.30796384811401367


In [4]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

# **Fancy Indexing**
Fancy indexing is the process of selecting multiple elements, rows, or columns using a list or array of indices.

Instead of selecting one index at a time, we provide multiple index numbers together.

The outer brackets [] are used for indexing.

Inside them, NumPy expects one object.

**That object can be:**

- a single integer,
- a slice,
- or a list/array of indices

In [5]:
# 1D
a = np.array([3, 5, 6, 7, 8, 0, 0, 0, 5])       
print(a[8])       # this is with normal indexing as we provide only one index

print()

print(a[[0, 2, 3, 6]])  # this is fancy indexing

5

[3 6 7 0]


In [6]:
# 2D
a = np.array([3, 5, 6, 7, 8, 0, 0, 0, 5]).reshape(3, 3)
# selecting rows and columns
print(a)
print()
print(a[[1]])  # row
print(a[:,[2]])   # column
print(a[0, [1, 2]])
 

[[3 5 6]
 [7 8 0]
 [0 0 5]]

[[7 8 0]]
[[6]
 [0]
 [5]]
[5 6]


In [7]:
# 2D
a = np.array([3, 5, 6, 7, 8, 0, 0, 0, 5]).reshape(3, 3)
print(a)
print(a[[0, 1, 2], [0, 1, 2]])               # select specific elements

print()
print(a[[0, 2], [0, 2]])  # take 0 from 0 and take 2 frome 2
print(a[[0,0,2,2], [0,2,0,2]])

[[3 5 6]
 [7 8 0]
 [0 0 5]]
[3 8 5]

[3 5]
[3 6 0 5]


In [8]:
#3D

b = np.arange(1, 28).reshape(3, 3, 3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [9]:
print(b[[0, 2], :, :])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [10]:
print(b[[0, 0, 0, 0, 2, 2, 2, 2], [0, 0, 2, 2, 0, 0, 2, 2], [0, 2, 0, 2, 0, 2, 0, 2]])

[ 1  3  7  9 19 21 25 27]


# **Bolean Indexing**
Boolean indexing selects elements using True and False values.

Every True keeps the element.

Every False removes it.

array[condition]

In [11]:
b = np.arange(1, 28).reshape(3, 3, 3)

print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
a = b[b>10]*10

print(b)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270]


In [13]:
b[b%2==0]=100
print(b)

[[[  1 100   3]
  [100   5 100]
  [  7 100   9]]

 [[100  11 100]
  [ 13 100  15]
  [100  17 100]]

 [[ 19 100  21]
  [100  23 100]
  [ 25 100  27]]]


In [14]:
b[b%2!=0]*=2

print(b)

[[[  2 100   6]
  [100  10 100]
  [ 14 100  18]]

 [[100  22 100]
  [ 26 100  30]
  [100  34 100]]

 [[ 38 100  42]
  [100  46 100]
  [ 50 100  54]]]


In [15]:
b[(b>5) & (b<20)]

array([ 6, 10, 14, 18])

In [16]:
b[(b%2==0) | (b%3==0)]

array([  2, 100,   6, 100,  10, 100,  14, 100,  18, 100,  22, 100,  26,
       100,  30, 100,  34, 100,  38, 100,  42, 100,  46, 100,  50, 100,
        54])

<br>

# **Broadcasting**

Broadcasting is NumPy's mechanism for performing element-wise operations on arrays of different shapes by automatically expanding the smaller array, without actually copying its data.

**Notice two important words:**
- Automatically expanding
- Without actually copying

Many beginners misunderstand broadcasting.

They think NumPy physically makes new copies of the smaller array.

It usually doesn't.

NumPy behaves as if the smaller array were expanded. Internally, it avoids unnecessary copies whenever possible, making broadcasting memory efficient.





### **Broadcasting Rules**

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.


<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [6]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print()
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [7]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)        # its does not perform broadcaste

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


<br>

# **Working with mathematical Formula**

In [22]:
# Sigmoid

a = np.arange(100)

def sigmoid(arr):
    return 1/(1+np.exp(-arr))

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [23]:
# Mean Square Error

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

def mse(actual, predicted):
    error = (actual - predicted)**2
    return np.mean(error)

mse(a, b)

np.float64(4.0)

<br>

# **Working with Null Values**

### **isnan**

In [27]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, np.nan, np.nan, 9])

print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8. nan nan  9.]


In [28]:
np.isnan(a)

array([False, False, False, False, False, False, False, False,  True,
        True, False])

In [29]:
# seeing null values
a[np.isnan(a)]

array([nan, nan])

In [32]:
# counting null values
np.isnan(a).sum()

np.int64(2)

In [34]:
# seeing without null value

a[~np.isnan(a)]

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
# replacing null values
a[np.isnan(a)]=0


In [47]:
arr = np.array([10,20,np.nan,40])

In [50]:
# replacing with mean
np.nanmean(arr)

# nanmean is used to calculate the mean by ignoring the null values

np.float64(23.333333333333332)

In [54]:
arr[np.isnan(arr)] = np.nanmean(arr)

In [57]:
print(np.round(arr, 2))

[10.   20.   23.33 40.  ]


<br>

---