<b><h1><center>Numpy Tricks</center></h1></b>

### **These are the some hidden function of numpy**

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [18]:
import numpy as np

arr = np.random.randint(1, 20, 25)

In [19]:
np.sort(arr)

array([ 2,  3,  4,  4,  5,  5,  6,  6,  6,  7,  8,  8,  8,  9, 11, 13, 14,
       16, 16, 17, 17, 17, 18, 19, 19], dtype=int32)

In [20]:
np.sort(arr)[::-1]   # to reverse the list

array([19, 19, 18, 17, 17, 17, 16, 16, 14, 13, 11,  9,  8,  8,  8,  7,  6,
        6,  6,  5,  5,  4,  4,  3,  2], dtype=int32)

In [21]:
# 1D array
arr = np.random.randint(1, 20, 25).reshape(5, 5)
print(arr)

[[ 1 10 19 19 14]
 [ 8 18  4 16 10]
 [ 2 17  7  2 10]
 [19  3 12 10 17]
 [17  3  5  9  4]]


In [22]:
np.sort(arr, axis=0)  # the default axis is 1

array([[ 1,  3,  4,  2,  4],
       [ 2,  3,  5,  9, 10],
       [ 8, 10,  7, 10, 10],
       [17, 17, 12, 16, 14],
       [19, 18, 19, 19, 17]], dtype=int32)

In [23]:
np.sort(arr, axis=1)

array([[ 1, 10, 14, 19, 19],
       [ 4,  8, 10, 16, 18],
       [ 2,  2,  7, 10, 17],
       [ 3, 10, 12, 17, 19],
       [ 3,  4,  5,  9, 17]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array, it work on the same dimension array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [24]:
arr = np.random.randint(1, 20, 25)
arr2 = np.array([2, 3, 4, 5, 6, 7])
arr

array([ 5,  6,  8, 12,  4,  7,  2, 13, 17, 10,  9, 18, 16, 10, 19,  3, 19,
       18,  9, 14,  5,  9,  6, 17, 13], dtype=int32)

In [25]:
np.append(arr, arr2)

array([ 5,  6,  8, 12,  4,  7,  2, 13, 17, 10,  9, 18, 16, 10, 19,  3, 19,
       18,  9, 14,  5,  9,  6, 17, 13,  2,  3,  4,  5,  6,  7])

In [26]:
# 2D
arr = np.random.randint(1, 20, 25).reshape(5, 5)
arr2 = np.array([2, 3, 4, 5, 6])
arr

array([[18,  3,  9, 11,  3],
       [ 9,  6,  8,  6,  7],
       [11, 14, 11, 19, 17],
       [ 3, 15, 19,  3, 11],
       [ 3, 13, 18,  7,  2]], dtype=int32)

In [27]:
np.append(arr, arr2.reshape(1,5), axis=0)

array([[18,  3,  9, 11,  3],
       [ 9,  6,  8,  6,  7],
       [11, 14, 11, 19, 17],
       [ 3, 15, 19,  3, 11],
       [ 3, 13, 18,  7,  2],
       [ 2,  3,  4,  5,  6]])

In [28]:
np.append(arr, np.arange(1, 6).reshape(5, 1), axis=1)

array([[18,  3,  9, 11,  3,  1],
       [ 9,  6,  8,  6,  7,  2],
       [11, 14, 11, 19, 17,  3],
       [ 3, 15, 19,  3, 11,  4],
       [ 3, 13, 18,  7,  2,  5]])

In [29]:
arr

array([[18,  3,  9, 11,  3],
       [ 9,  6,  8,  6,  7],
       [11, 14, 11, 19, 17],
       [ 3, 15, 19,  3, 11],
       [ 3, 13, 18,  7,  2]], dtype=int32)

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [30]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [31]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [33]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [34]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [35]:
# code
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.expand_dims(a, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
np.expand_dims(a, axis=0)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

np.where(condition, if_true, if_false )

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [38]:
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [39]:
np.where(a>10, 0, a)

array([0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 9, 0, 2, 0])

In [40]:
import numpy as np
marks = np.array([45,80,30,90])

grade = np.where(
    marks>=50,
    "Pass",
    "Fail"
)

print(grade)

['Fail' 'Pass' 'Fail' 'Pass']


### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [41]:
# code
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [42]:
np.argmax(a)

np.int64(6)

In [43]:
a[6]

np.int64(94)

In [44]:
# np.argmin
np.argmin(a)

np.int64(13)

In [45]:
a[13]

np.int64(2)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [46]:
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [47]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [48]:
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21]).reshape(3, 5)
a

array([[11, 53, 28, 50, 38],
       [37, 94, 92,  5, 30],
       [68,  9, 78,  2, 21]])

In [49]:
np.cumsum(a, axis=0)

array([[ 11,  53,  28,  50,  38],
       [ 48, 147, 120,  55,  68],
       [116, 156, 198,  57,  89]])

In [50]:
# np.cumprod
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [51]:
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [52]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [53]:
np.percentile(a,50)

np.float64(37.0)

In [54]:
np.median(a)

np.float64(37.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [55]:
# code
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])


In [56]:
x, y = np.histogram(a, bins=[0, 10, 20, 30, 40, 50])


In [57]:
x, y

(array([3, 1, 2, 3, 1]), array([ 0, 10, 20, 30, 40, 50]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [58]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [59]:
# code
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])



In [60]:
np.isin(a, 45)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [61]:
x = np.isin(a, [44, 34, 79, 2])

print(x)

a[x]

[False False False False False False False False False False False False
 False  True False]


array([2])

In [62]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a, items)]

array([50, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [63]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [64]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [65]:
b = np.array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [66]:
np.flip(b,axis=0)

array([[40, 71,  2,  7],
       [ 8, 87, 31, 72],
       [38, 63, 44, 85],
       [61, 93, 83,  9],
       [29, 18, 47, 55],
       [12, 52, 42,  6]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [67]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [68]:
np.put(a, 0, 20)
a

array([20, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [69]:
np.put(a,[0,1],[110,530])
np.put(a, [-2,-1], [0, 0])
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         0,   0])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [70]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         0,   0])

In [71]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   0,   0])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [72]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
np.intersect1d(m,n)

array([3, 4, 5])

In [74]:
np.setdiff1d(n,m)

array([6, 7])

In [75]:
np.setxor1d(m,n)     # give all except common

array([1, 2, 6, 7])

In [76]:
m[np.in1d(m,1)]

C:\Users\HP\AppData\Local\Temp\ipykernel_63088\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

np.clip(arr, min_value, max_value)

np.clip(arr,None,50)  We can also use None in place if we did not use any limit as here is no upper limit.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [77]:
# code
a


array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         0,   0])

In [78]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

### np.count_nonzero
count all non zero

In [79]:
print(a)



[110 530  28  50  38  37  94  92   5  30  68   9  78   0   0]


In [80]:
np.count_nonzero(a)

np.int64(13)

### np.repeat
repeat the element of array

In [81]:
import numpy as np
a = np.array([2, 3, 4, 5])

np.repeat(a, 2)

array([2, 2, 3, 3, 4, 4, 5, 5])

### np.tile
repeat the whole array

In [82]:
np.tile(a, 2)

array([2, 3, 4, 5, 2, 3, 4, 5])

### np.all
return true if all are true

In [83]:
arr = np.array([True, False, True])

print(np.all(arr))

False


### np.any
return true if any are true

In [84]:
arr = np.array([True, False, True])

print(np.any(arr))

True


### np.ravel
convert an array into 1d just for view as it connect to the original array and it we make some changes in the converted array then it will be also apply on the original array

In [85]:
a = np.arange(1,10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
b = np.ravel(a)
print(b)
b[0]=100
print(b)
print(a)      # notice it also change the original array

[1 2 3 4 5 6 7 8 9]
[100   2   3   4   5   6   7   8   9]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


### obj.flatten
it create a new array and not connected with original array and work same as ravel

In [87]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

b = a.flatten()
print(b)
b[0]=1000
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1000    2    3    4    5    6    7    8    9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<br>

---