### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
# code here

import numpy as np

a = np.array([[92, 90, 74],
            [6, 63, 93],
            [15, 93, 96],
            [70, 60, 48]])

np.sort(a)


array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [2]:
ind = np.argsort(a[:, 1])
# ind
a[[ind]]


array([[[70, 60, 48],
        [ 6, 63, 93],
        [92, 90, 74],
        [15, 93, 96]]])

In [3]:
ind = np.max(a, axis=1).argsort()[::-1]
a[[ind]]

array([[[15, 93, 96],
        [ 6, 63, 93],
        [92, 90, 74],
        [70, 60, 48]]])

In [4]:
np.sort(a, axis=None)

array([ 6, 15, 48, 60, 63, 70, 74, 90, 92, 93, 93, 96])

### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [5]:
# code here

marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([[41, 87, 72, 36, 92]])

marks = np.concatenate((marks,extra_subject.reshape(5,1)), axis=1)

rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])
marks = np.concatenate((marks, rec1.reshape(1, -1), rec2.reshape(1, -1)), axis=0)
sums = np.sum(marks, axis=1)
marks = np.concatenate((marks, sums.reshape(-1, 1)), axis=1)
ind = marks[:, -1].argsort()[::-1]
print(marks[[ind]])


[[[ 77  83  98  95  89 442]
  [ 92  71  52  61  53 329]
  [ 63  46  90  42  87 328]
  [ 67  61  59  36  92 315]
  [ 82   9  29  78  36 234]
  [ 39  76  13  29  72 229]
  [ 13  10   9  33  41 106]]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [6]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])


np.unique(arr, axis=0)
np.unique(arr, axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [7]:
# code here

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

a = np.flip(arr, axis=0)
np.flip(a, axis=1)



array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [8]:
# code here

arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
x = 6
bol = arr>x
rows = np.any(bol, axis=1)
a, = np.where(rows)
above_x = arr[a]
print(above_x)
print(above_x.shape[0])
a

[[10 -3 30  4  5]
 [ 9  7  3  6  5]]
2


array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [9]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

print(arr1)
print(arr2)
print(arr3)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [10]:
# code here

a = np.concatenate((arr1, arr2, arr3), axis=0)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [11]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [12]:

arr = np.delete(arr, arr.argmax(axis=1), axis=1)

arr = np.delete(arr, arr.argmin(axis=1), axis=1)
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
        782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
        308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
        230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
        227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
        575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
        525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
        786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
        453, 193, 607, 677, 637, 728, 724, 534, 748

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [55]:
# code here
import numpy as np

np.random.seed(20)
arr = np.random.randint(100, 700, 300)

arr = np.clip(arr, 100, 200)
arr = np.sort(arr)

cumsum_arr = np.cumsum(arr)
print(cumsum_arr)
print(arr)


[  104   209   315   426   537   649   764   892  1029  1168  1307  1447
  1588  1730  1873  2016  2164  2312  2462  2613  2773  2934  3098  3262
  3428  3595  3763  3932  4102  4275  4450  4628  4807  4989  5174  5360
  5546  5733  5929  6125  6322  6521  6721  6921  7121  7321  7521  7721
  7921  8121  8321  8521  8721  8921  9121  9321  9521  9721  9921 10121
 10321 10521 10721 10921 11121 11321 11521 11721 11921 12121 12321 12521
 12721 12921 13121 13321 13521 13721 13921 14121 14321 14521 14721 14921
 15121 15321 15521 15721 15921 16121 16321 16521 16721 16921 17121 17321
 17521 17721 17921 18121 18321 18521 18721 18921 19121 19321 19521 19721
 19921 20121 20321 20521 20721 20921 21121 21321 21521 21721 21921 22121
 22321 22521 22721 22921 23121 23321 23521 23721 23921 24121 24321 24521
 24721 24921 25121 25321 25521 25721 25921 26121 26321 26521 26721 26921
 27121 27321 27521 27721 27921 28121 28321 28521 28721 28921 29121 29321
 29521 29721 29921 30121 30321 30521 30721 30921 31

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [115]:
# code here
np.random.seed(10)
a = np.random.random(100)
a = np.round(a, 3)

mini = np.min(a)

per_0 = np.percentile(a, 0)

print(mini==per_0)

maxi = np.max(a)

per_100 = np.percentile(a, 100)

np.round(np.mean(a), 3)

per_50 = np.percentile(a, 50)
# per_50
per_51 = np.percentile(a, 51)

np.round(per_51-per_50, 3)

True


np.float64(0.008)